### ISSUE TITLE
Limited to HTTP text-based requests & responses

### ISSUE THREAD

**Issue by atifaziz** [lecaillon/Cassette#23]
The [project intro](https://github.com/lecaillon/Cassette/blob/1.0.0/README.md) reads as if this is designed for general-purpose HTTP recording and playback:

> Records and replays successful HTTP responses in your testing environment.
> 
> In a micro-service context, where your integration tests depend on a lot of external HTTP resources, Cassette is an ideal tool to improve the stability of your CI pipeline. It is based on a very simple idea: uniquely identify all the requests that pass through and record succesfull reponses. After recording, replay the same responses without actually calling the real REST endpoint.
> 
> To create that unique request identifier, Cassette computes an hash from the HTTP method, the uri and the body.

There is no mention of it being limited to _textual_ HTTP resources, which is somewhat misleading. On close inspection, one see that [`Request.Body`](https://github.com/lecaillon/Cassette/blob/1f2b463686b835ae8264b1b9870ff5170f2688db/src/Cassette/Cassette.cs#L107) and [`Response.Body`](https://github.com/lecaillon/Cassette/blob/1f2b463686b835ae8264b1b9870ff5170f2688db/src/Cassette/Cassette.cs#L118) are typed as `string`. If the scope of the project is API endpoints accepting and returning textual entities then the README should be updated to mention the limitation/scope.

Having said that, I didn't see any reason for the limitation. A quick spike showed that a few tweaks can have the library can working without regard to he content media type. I'd be happy to submit the results as a PR if you'd welcome that.

**Comment by lecaillon** [comment]
Totally right, great idea. Thanks for the feedback. Waiting for your MR ;)

**Comment by atifaziz** [comment]
> Waiting for your MR ;)

Done. See PR #24.

**Comment by lecaillon** [comment]
By the way, if you think the readme isn't clear enough or can be improved in anyway, feel free to submit a PR too.

**Comment by atifaziz** [comment]
Closed via 5c485c119ec1d862661633f95ec1f5154326a7e9.
